### ISSUE TITLE
Reduce magic variables usage

### ISSUE THREAD

**Issue by raphaelstolt** [jonathantorres/construct#101]
We should reduce the usage of magic variables (e.g. defaults in [ConstructCommand](https://github.com/jonathantorres/construct/blob/master/src/Commands/ConstructCommand.php#L218)).

**Comment by jonathantorres** [comment]
We could add them as constants to the [Defaults.php](https://github.com/jonathantorres/construct/blob/master/src/Defaults.php) class.
