### ISSUE TITLE
Align wording for linked ressources in README.md

### ISSUE THREAD

**Issue by raphaelstolt** [jonathantorres/construct#112]
There's currently a mixture of `.. for more details.` and `.. for more information.` when linking to ressources (e.g. changelog, contributing) in the [README.md](https://github.com/jonathantorres/construct/blob/master/src/stubs/README.stub). Would suggest to pick one and use it consistently. Which one would you prefer?

**Comment by jonathantorres** [comment]
I would prefer `for more details`
