### ISSUE TITLE
interactive mode

### ISSUE THREAD

**Issue by staabm** [jonathantorres/construct#14]
would be great to have a interactive mode where construct asks the user for all required (and also optional information) with some sane defaults pre-selected

**Comment by hannesvdvreken** [comment]
You could use http://symfony.com/doc/current/components/console/helpers/questionhelper.html

**Comment by Anahkiasen** [comment]
:+1: for this

**Comment by jonathantorres** [comment]
Feature added on latest release: https://github.com/jonathantorres/construct/releases/tag/v1.7.0 :dancer:
