### ISSUE TITLE
Installation failure due to package requirement resolution conflict

### ISSUE THREAD

**Issue by sasindumendis** [jonathantorres/construct#67]
![screenshot from 2015-08-29 22 48 47](https://cloud.githubusercontent.com/assets/2373211/9563402/2e726a24-4ea0-11e5-83a7-83bfa2049ddb.png)

I have two other composer packages globally installed (namely `fabpot/php-cs-fixer` and `laravel/installer`) that have `"symfony/console": "~2.3"` as their requirement.

What is the best way to go about this?

**Comment by jonathantorres** [comment]
I think it's because construct was requiring strictly 2.6.\* of symfony console. Just pushed an update to require the latest stable version. Just run `composer global require jonathantorres/construct` again and you should be good to go.

**Comment by sasindumendis** [comment]
Thank you for the quick response!
Can you please update the `illuminate/*` requirements to `5.1.*` as well?

**Comment by jonathantorres** [comment]
I can't. I want to support at least php `5.4.0`. Illuminate `5.1.*` requires at least php `5.5.9`. I might update them for the next major version.
