### ISSUE TITLE
Cannot install due to dependencies  symfony/finder multi version [v2.6.0, v2.7.3].

### ISSUE THREAD

**Issue by sunel** [jonathantorres/construct#68]
$ composer global require jonathantorres/construct
Changed current directory to E:/users/sunel.saminathan/AppData/Roaming/Composer
Using version ^1.4 for jonathantorres/construct
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install jonathantorres/construct v1.4.1
    - Conclusion: remove symfony/finder v2.7.3
    - Installation request for jonathantorres/construct ^1.4 -> satisfiable by j
onathantorres/construct[v1.4.0, v1.4.1].
    - Conclusion: don't install symfony/finder v2.7.3
    - jonathantorres/construct v1.4.0 requires illuminate/filesystem 5.0.\* -> sa
tisfiable by illuminate/filesystem[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v
5.0.33, v5.0.4].
    - illuminate/filesystem v5.0.0 requires symfony/finder 2.6.\* -> satisfiable
by symfony/finder[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.6
.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - illuminate/filesystem v5.0.22 requires symfony/finder 2.6.\* -> satisfiable
 by symfony/finder[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.
6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - illuminate/filesystem v5.0.25 requires symfony/finder 2.6.\* -> satisfiable
 by symfony/finder[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.
6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - illuminate/filesystem v5.0.26 requires symfony/finder 2.6.\* -> satisfiable
 by symfony/finder[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.
6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - illuminate/filesystem v5.0.28 requires symfony/finder 2.6.\* -> satisfiable
 by symfony/finder[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.
6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - illuminate/filesystem v5.0.33 requires symfony/finder 2.6.\* -> satisfiable
 by symfony/finder[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.
6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - illuminate/filesystem v5.0.4 requires symfony/finder 2.6.\* -> satisfiable
by symfony/finder[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.6
.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - Can only install one of: symfony/finder[v2.6.0, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.1, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.10, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.11, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.2, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.3, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.4, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.5, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.6, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.7, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.8, v2.7.3].
    - Can only install one of: symfony/finder[v2.6.9, v2.7.3].
    - Installation request for symfony/finder == 2.7.3.0 -> satisfiable by symfo
ny/finder[v2.7.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by jonathantorres** [comment]
Can I see your global composer.json file? To see if I can replicate?

**Comment by sunel** [comment]
Its just default global composer.json file no other package added to it

**Comment by pmatseykanets** [comment]
@jonathantorres I'm experiencing the same issue.

My global composer.json shows

```
➜  src  cat ~/.composer/composer.json
{
    "require": {
        "laravel/installer": "~1.1",
        "laravel/homestead": "~2.0",
        "laravel/lumen-installer": "~1.0",
        "franzl/studio": "^0.9.5",
        "phpmd/phpmd": "@stable",
        "fabpot/php-cs-fixer": "^1.10"
    }
}
```

**Comment by sunel** [comment]
When i tried in OSX it installed fine , But the problem occurred in Windows

**Comment by jonathantorres** [comment]
@sunel I see. I'll debug on a Windows machine. My first guess it's an issue with illuminate components.

@pmatseykanets are you also on Windows?

**Comment by pmatseykanets** [comment]
@jonathantorres No, I'm on OS X. I don't think it has anything to do with the OS.

**Comment by jonathantorres** [comment]
Just released a patch. Try to install again `composer global require jonathantorres/construct`

**Comment by sunel** [comment]
:thumbsup: its working now

**Comment by pmatseykanets** [comment]
Thank you @jonathantorres. It's working for me now too.

**Comment by jonathantorres** [comment]
Awesome :+1:
