### ISSUE TITLE
It's possible to select a PHP version greater than the one the project is constructed on

### ISSUE THREAD

**Issue by raphaelstolt** [jonathantorres/construct#77]
This leads to problems (like shown in the following console excerpt) when doing the `composer install`. 

``` bash
Creating your project...
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=5.6.0 but your PHP version (5.5.9) does not satisfy that requirement.
```

**Comment by jonathantorres** [comment]
Perhaps instead of using `5.6.0` by default, construct should use the php version that it's installed when the command is executed.

**Comment by raphaelstolt** [comment]
Yes the default PHP version should be the one used on the `constructing` system, and it shouldn't be possible to choose one greater than it.

**Comment by jonathantorres** [comment]
Agreed.
