### ISSUE TITLE
Don't set the required PHP version to the exact patch version

### ISSUE THREAD

**Issue by raphaelstolt** [jonathantorres/construct#85]
Just had an [issue](https://travis-ci.org/raphaelstolt/json-lines/jobs/111879643#L157) with Travis CI where the in Composer required PHP version (set via `construct`) was greater than the version on the Travis CI box. Maybe we should just pinpoint the PHP version to the minor version.

**Comment by jonathantorres** [comment]
I see, perhaps construct should also support feature versions as well, so you can do something like: `construct generate vendor/project --php=5.6`

But if you do `construct generate vendor/project --php=5.6.0` everything should work fine.
