### ISSUE TITLE
Add new feature to load common option settings from configuration file

### ISSUE THREAD

**Issue by raphaelstolt** [jonathantorres/construct#86]
What's your opinion on adding an optional option to load common options settings (e.g. `namespace`, `testing framework`, `editor config`, ...), which might be standardised for a company or organisation, from a configuration file?

``` bash
 -c, --configuration[=CONFIGURATION]  Generate from configuration file [default: "/home/<username>/.construct"]
```

Which configuration format (e.g. `ini`, `yaml`, `toml`, `json`) would you prefer?

**Comment by jonathantorres** [comment]
I'm definitely not against it. If you have the time, go for it! I would prefer the `yaml` format.
