### ISSUE TITLE
Rename test option to test-framework

### ISSUE THREAD

**Issue by raphaelstolt** [jonathantorres/construct#96]
To avoid a confusion with the activity `test`ing we should prolly rename the long option to `testing-framework`, also aligns it with the used configuration key.

**Comment by jonathantorres** [comment]
What do you mean with "activity testing"?

I think we can add `testing-framework` as another way of saying `test` (like an alias)

**Comment by raphaelstolt** [comment]
I mean that the option test might get confused with actually running the tests though it's meant to choose a testing framework.

**Comment by raphaelstolt** [comment]
Sorry for the inconsistency. Fixed the option name / alias now to `test-framework`. See #98.
